version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install pyinstaller
      - run:
          name: Build APK
          command: |
            pyinstaller --name my_app --add-data "resources/*:resources" --clean --noconfirm --log-level=DEBUG app.py
            mkdir output
            mv dist/my_app output/my_app
      - store_artifacts:
          path: output
          destination: my_app
